overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@sveltejs/kit@>=2.19.0 <=2.49.4': '>=2.49.5'
  '@sveltejs/kit@>=2.49.0 <=2.49.4': '>=2.49.5'
  cookie@<0.7.0: '>=0.7.0'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
